#ifndef __IMATH_H__
#define __IMATH_H__

#include <ImathBox.h>
#include <ImathBoxAlgo.h>
#include <ImathColor.h>
#include <ImathColorAlgo.h>
#include <ImathConfig.h>
#include <ImathEuler.h>
#include <ImathExport.h>
#include <ImathForward.h>
#include <ImathFrame.h>
#include <ImathFrustum.h>
#include <ImathFrustumTest.h>
#include <ImathFun.h>
#include <ImathGL.h>
#include <ImathGLU.h>
#include <ImathInt64.h>
#include <ImathInterval.h>
#include <ImathLine.h>
#include <ImathLineAlgo.h>
#include <ImathMath.h>
#include <ImathMatrix.h>
#include <ImathMatrixAlgo.h>
#include <ImathNamespace.h>
#include <ImathPlane.h>
#include <ImathPlatform.h>
#include <ImathQuat.h>
#include <ImathRandom.h>
#include <ImathRoots.h>
#include <ImathShear.h>
#include <ImathSphere.h>
#include <ImathTypeTraits.h>
#include <ImathVec.h>
#include <ImathVecAlgo.h>
#include <half.h>
#include <halfFunction.h>
#include <halfLimits.h>
#include <toFloat.h>

#endif // __IMATH_H__
